// Embeds the Creative Engine's pinned fonts into
// supabase/functions/creative-engine/fonts.generated.ts (base64 + sha256), so
// the Edge Function and the Node tests read the same bytes with no file
// access at runtime. Source: the exact @fontsource versions in package.json
// (OFL-1.1; licences copied next to the module). Re-run after changing a
// pinned version; the renderer version must change with it.
//   node scripts/creative-fonts.mjs
import fs from "node:fs";
import crypto from "node:crypto";

const FONTS = [
  ["montserrat-700", "@fontsource/montserrat", "montserrat-latin-700-normal.woff", "Montserrat", 700],
  ["montserrat-800", "@fontsource/montserrat", "montserrat-latin-800-normal.woff", "Montserrat", 800],
  ["poppins-500", "@fontsource/poppins", "poppins-latin-500-normal.woff", "Poppins", 500],
  ["poppins-600", "@fontsource/poppins", "poppins-latin-600-normal.woff", "Poppins", 600],
];
const root = new URL("../", import.meta.url);
const out = new URL("supabase/functions/creative-engine/fonts.generated.ts", root);
const lines = [
  "// GENERATED by scripts/creative-fonts.mjs — do not edit by hand.",
  "// Pinned Creative Engine fonts (OFL-1.1; see ./fonts/). Latin subsets from @fontsource.",
  "export type EmbeddedFont = { id: string; family: string; weight: number; source: string; sha256: string; base64: string };",
  "export const EMBEDDED_FONTS: EmbeddedFont[] = [",
];
for (const [id, pkg, file, family, weight] of FONTS) {
  const dir = new URL(`node_modules/${pkg}/`, root);
  const version = JSON.parse(fs.readFileSync(new URL("package.json", dir), "utf8")).version;
  const bytes = fs.readFileSync(new URL(`files/${file}`, dir));
  const sha = crypto.createHash("sha256").update(bytes).digest("hex");
  lines.push(`  { id: ${JSON.stringify(id)}, family: ${JSON.stringify(family)}, weight: ${weight}, source: ${JSON.stringify(`${pkg}@${version}/files/${file}`)}, sha256: ${JSON.stringify(sha)},`);
  lines.push(`    base64: ${JSON.stringify(bytes.toString("base64"))} },`);
  fs.copyFileSync(new URL("LICENSE", dir), new URL(`supabase/functions/creative-engine/fonts/${family}-OFL.txt`, root));
}
lines.push("];", "");
fs.writeFileSync(out, lines.join("\n"));
console.log(`wrote ${out.pathname}`);
